const CATS=['For Tyler','Men','Women','Kids','Clothing','Home','Kitchen','Kids & Toys','Beauty','Pets','Tools','Tech','Saved'];
let cat='For Tyler',renderLimit=120,verifyObserver=null;
let products=JSON.parse(localStorage.getItem('luxMobileProducts')||'[]');
let favs=new Set(JSON.parse(localStorage.getItem('luxMobileFavs')||'[]'));
if(localStorage.getItem('luxMobileVersion')!=='1.3'){products=products.map(p=>({...p,active:false,stock:'unknown',imageVerified:false}));localStorage.setItem('luxMobileVersion','1.3');saveState()}
const money=n=>'$'+Number(n||0).toFixed(2),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const disc=p=>Number(p.discount)||((p.was&&p.was>p.price)?Math.round((1-p.price/p.was)*100):0),sav=p=>Number(p.save||p.savings)||((p.was&&p.was>p.price)?p.was-p.price:0);
function audience(p){if(p.audience)return p.audience;const s=[p.name,p.sub,p.categoryRaw].join(' ').toLowerCase();if(/\b(girl|boy|kid|youth|child|toddler)\b/.test(s))return'Kids';if(/\b(women|woman|ladies)\b/.test(s))return'Women';if(/\b(men|mens|male)\b/.test(s))return'Men';return'Unisex'}
function categoryOf(name='',path=''){const s=(name+' '+path).toLowerCase();if(/shirt|tee\b|dress|jeans|pants|shorts|legging|hoodie|sweater|jacket|shoe|sneaker|pajama|top\b|apparel|fashion/.test(s))return'Clothing';if(/lego|toy\b|doll|barbie|game\b|puzzle|hot wheels/.test(s))return'Kids & Toys';if(/cookware|skillet|kitchen|blender|coffee|tumbler|bowl|plate/.test(s))return'Kitchen';if(/shampoo|hair|makeup|beauty|scrunchie|skincare/.test(s))return'Beauty';if(/dog|cat\b|pet\b|puppy|kitten/.test(s))return'Pets';if(/drill|saw\b|tool\b|vacuum|faucet|hart\b/.test(s))return'Tools';if(/laptop|phone|tv\b|earbud|headphone|charger|electronics/.test(s))return'Tech';if(/mattress|towel|pillow|blanket|lamp|decor|rug\b|bedding|furniture|storage|home\b/.test(s))return'Home';return'Other'}
function score(p){let n=Number(p.score)||0;if(audience(p)==='Men')n+=22;else if(['Home','Kitchen','Tools','Tech','Pets'].includes(p.category))n+=5;return Math.min(125,n)}
function level(p){const d=disc(p),s=score(p);return d>=65||(p.price<=3&&d>=35)||s>=88?'ABSURD':d>=45||s>=68?'STEAL':'WORTH IT'}
function saveState(){localStorage.setItem('luxMobileProducts',JSON.stringify(products));localStorage.setItem('luxMobileFavs',JSON.stringify([...favs]))}
function chips(){document.getElementById('chips').innerHTML=CATS.map(c=>`<button class="chip ${c===cat?'on':''}" onclick="setCat('${c}')">${c==='For Tyler'?'✦ ':''}${c}</button>`).join('')}
function setCat(c){cat=c;renderLimit=120;chips();render();window.scrollTo({top:document.getElementById('chips').offsetTop-60,behavior:'smooth'})}
function filtered(){const q=document.getElementById('q').value.trim().toLowerCase(),max=+document.getElementById('max').value;let a=products.filter(p=>p.active!==false&&p.stock==='in'&&+p.price<=max);if(cat==='Saved')a=a.filter(p=>favs.has(String(p.id)));else if(cat==='Men'||cat==='Women'||cat==='Kids')a=a.filter(p=>audience(p)===cat);else if(cat!=='For Tyler')a=a.filter(p=>(p.category||p.cat)===cat);if(q)a=a.filter(p=>[p.name,p.brand,p.category,p.sub,audience(p)].join(' ').toLowerCase().includes(q));const so=document.getElementById('sort').value;if(so==='score')a.sort((x,y)=>score(y)-score(x)||x.price-y.price);if(so==='discount')a.sort((x,y)=>disc(y)-disc(x));if(so==='save')a.sort((x,y)=>sav(y)-sav(x));if(so==='price')a.sort((x,y)=>x.price-y.price);return a}
function card(p){const l=level(p),d=disc(p),sv=sav(p);return `<article class="card" data-verify="${p.id}"><div class="photo" onclick="openItem('${p.id}')">${p.image&&p.imageVerified?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:`<div class="noimg">Verifying exact Walmart photo…</div>`}<span class="badge ${l==='ABSURD'?'absurd':l==='STEAL'?'steal':''}">${l}${d?' · '+d+'%':''}</span><button class="fav" onclick="event.stopPropagation();toggleFav('${p.id}')">${favs.has(String(p.id))?'♥':'♡'}</button><span class="seller">${/walmart/i.test(p.seller||'')?'✓ Walmart':'Check seller'}</span></div><div class="body"><div class="eyebrow">${esc(audience(p))} · ${esc(p.category||'Other')} · score ${score(p)}</div><div class="name" onclick="openItem('${p.id}')">${esc(p.brand||'')} ${esc(p.name)}</div><div class="priceRow"><span class="price">${money(p.price)}</span>${p.was?`<span class="was">${money(p.was)}</span>`:''}${sv?`<span class="save">save ${money(sv)}</span>`:''}</div><div class="rating">${p.rating?`★ ${Number(p.rating).toFixed(1)} · ${Number(p.reviews||0).toLocaleString()} ratings`:''}</div><div class="tags">${audience(p)==='Men'?'<span class="tag">Tyler · M/L</span>':''}${audience(p)==='Kids'?'<span class="tag">ages 9/11/16</span>':''}</div><div class="actions"><button onclick="openItem('${p.id}')">View</button><a href="${esc(p.url)}" target="_blank">Walmart ↗</a></div></div></article>`}
function render(){const a=filtered(),shown=a.slice(0,renderLimit);document.getElementById('grid').innerHTML=shown.length?shown.map(card).join(''):'<div class="empty">No verified in-stock deals in this filter. Run Scan.</div>';if(a.length>shown.length)document.getElementById('grid').insertAdjacentHTML('beforeend',`<div class="empty"><button onclick="renderLimit+=120;render()">Load more</button><p>${shown.length} of ${a.length} shown</p></div>`);document.getElementById('heading').textContent=cat;document.getElementById('meta').textContent=`${shown.length} of ${a.length} live`;document.getElementById('total').textContent=products.filter(p=>p.active!==false&&p.stock==='in').length;document.getElementById('menN').textContent=products.filter(p=>p.active!==false&&p.stock==='in'&&audience(p)==='Men').length;document.getElementById('savedN').textContent=favs.size;observeVerify()}
function toggleFav(id){id=String(id);favs.has(id)?favs.delete(id):favs.add(id);saveState();render()}
function closeDetail(){document.getElementById('sheetBg').classList.remove('on')}
async function openItem(id){let p=products.find(x=>String(x.id)===String(id));if(!p)return;await verifyProduct(p,true);p=products.find(x=>String(x.id)===String(id)&&x.active!==false&&x.stock==='in');if(!p){render();return}document.getElementById('detail').innerHTML=`<div class="detailPic" id="detailPic">${p.image&&p.imageVerified?`<img src="${esc(p.image)}">`:'<div class="noimg">Exact image unavailable</div>'}</div><div class="eyebrow" style="margin-top:12px">${esc(audience(p))} · ${esc(p.category)} · ${level(p)} · IN STOCK</div><h1>${esc(p.brand||'')} ${esc(p.name)}</h1><div><span class="bigPrice">${money(p.price)}</span> ${p.was?`<span class="was">${money(p.was)}</span>`:''}</div><div class="panel"><b>Live verified</b><br>Product page checked before showing this detail. Out-of-stock products are removed automatically.</div><div class="detailBtns"><button onclick="toggleFav('${p.id}');openItem('${p.id}')">${favs.has(String(p.id))?'♥ Saved':'♡ Save'}</button><a href="${esc(p.url)}" target="_blank">Check / buy ↗</a></div>`;document.getElementById('sheetBg').classList.add('on')}
async function webFetch(url){if(window.AndroidBridge&&AndroidBridge.fetchText)return await nativeFetch(url);const reader='https://r.jina.ai/http://'+url.replace(/^https?:\/\//,'');const r=await fetch(reader);if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}
let nativeWait={};window.__nativeFetchResult=(token,ok,text)=>{const w=nativeWait[token];if(!w)return;delete nativeWait[token];ok?w.resolve(text):w.reject(new Error(text||'fetch failed'))};function nativeFetch(url){return new Promise((resolve,reject)=>{const token=Math.random().toString(36).slice(2)+Date.now();nativeWait[token]={resolve,reject};AndroidBridge.fetchText(url,token)})}
function stockText(s=''){if(/OUT_OF_STOCK|OUT OF STOCK|SOLD_OUT|UNAVAILABLE|"isOutOfStock"\s*:\s*true/i.test(s))return'out';if(/IN_STOCK|IN STOCK|ADD_TO_CART|"isOutOfStock"\s*:\s*false|shipping arrives|pickup today|delivery today/i.test(s))return'in';return'unknown'}
function idFromUrl(u=''){return String(u).match(/\/ip\/(?:[^/?#]+\/)?(\d{5,})/)?.[1]||String(u).match(/\/ip\/(\d{5,})/)?.[1]||''}
function clean(s=''){return String(s).replace(/\\u002F/g,'/').replace(/\\\//g,'/').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim()}
function firstNum(vals){for(const v of vals){const n=Number(String(v??'').replace(/[^0-9.]/g,''));if(Number.isFinite(n)&&n>0)return n}return 0}
function finish(p){p.category=p.category||categoryOf(p.name,p.categoryRaw||'');p.audience=p.audience||audience(p);p.was=p.was&&p.was>p.price?+p.was:null;p.discount=p.was?Math.round((1-p.price/p.was)*100):0;p.savings=p.was?Math.round((p.was-p.price)*100)/100:0;p.active=p.stock==='in';p.lastSeen=Date.now();return p}
function looseProducts(html,source){const out=[],rx=/["']usItemId["']\s*:\s*["'](\d{5,})["']/g;let m;while((m=rx.exec(html))){const b=html.slice(Math.max(0,m.index-2500),Math.min(html.length,m.index+7500));const pick=r=>clean(b.match(r)?.[1]||'');const name=pick(/["'](?:name|productName|title)["']\s*:\s*["']([^"']{3,220})["']/);const price=firstNum([pick(/["']currentPrice["']\s*:\s*\{[^{}]{0,600}?["']price["']\s*:\s*([0-9.]+)/),pick(/["']price["']\s*:\s*([0-9.]+)/)]);const stock=stockText(b);if(!name||!price||stock!=='in')continue;const was=firstNum([pick(/["']wasPrice["']\s*:\s*\{[^{}]{0,500}?["']price["']\s*:\s*([0-9.]+)/)]);let url=pick(/["'](?:canonicalUrl|productUrl)["']\s*:\s*["']([^"']+)["']/);if(url.startsWith('/'))url='https://www.walmart.com'+url;if(!url)url='https://www.walmart.com/ip/'+m[1];out.push(finish({id:m[1],name,price,was,url,image:'',imageVerified:false,seller:pick(/["']sellerName["']\s*:\s*["']([^"']+)["']/)||'Check seller',stock:'in',source}))}const map=new Map();for(const p of out)map.set(String(p.id),p);return[...map.values()]}
function discoverLanes(html){const doc=new DOMParser().parseFromString(html,'text/html'),out=[],seen=new Set();for(const a of doc.querySelectorAll('a[href]')){let u;try{u=new URL(a.getAttribute('href'),'https://www.walmart.com')}catch{continue}if(u.hostname!=='www.walmart.com')continue;const txt=(u.pathname+' '+u.search+' '+a.textContent).toLowerCase();if(!txt.includes('clearance')||u.pathname.includes('/ip/'))continue;u.searchParams.delete('page');u.searchParams.delete('affinityOverride');['povid','athAsset'].forEach(k=>u.searchParams.delete(k));const key=u.toString();if(seen.has(key))continue;seen.add(key);out.push({url:key,label:clean(a.textContent)||'Clearance lane',priority:/men|mens|men's/.test(txt)?90:60})}return out}
function pageUrl(base,page){const u=new URL(base);u.searchParams.delete('page');u.searchParams.delete('affinityOverride');if(page>1){u.searchParams.set('affinityOverride','default');u.searchParams.set('page',String(page))}return u.toString()}
async function verifyProduct(p,force=false){if(!force&&p.verifiedAt&&Date.now()-p.verifiedAt<2*3600e3&&p.imageVerified)return p;try{const html=await webFetch(p.url),st=stockText(html);if(st!=='in'){p.stock=st;p.active=false;p.verifiedAt=Date.now();saveState();return p}const img=clean(html.match(/<meta[^>]+(?:property|name)=["'](?:og:image|twitter:image)["'][^>]+content=["']([^"']+)["']/i)?.[1]||'');if(img.includes('walmartimages.com')){p.image=img;p.imageVerified=true}p.stock='in';p.active=true;p.verifiedAt=Date.now();saveState();return p}catch{return p}}
function observeVerify(){verifyObserver?.disconnect();verifyObserver=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;verifyObserver.unobserve(e.target);const p=products.find(x=>String(x.id)===e.target.dataset.verify);if(p&&(!p.verifiedAt||Date.now()-p.verifiedAt>2*3600e3||!p.imageVerified))verifyProduct(p).then(render)}),{rootMargin:'300px'});document.querySelectorAll('[data-verify]').forEach(x=>verifyObserver.observe(x))}
async function scanNow(){const t=document.getElementById('scanTitle'),st=document.getElementById('scanText');t.textContent='Exhaustive scan running…';const scanId='m-'+Date.now(),queue=[{url:'https://www.walmart.com/browse/clothing/mens/clearance/5438_9360765_9658256',label:'Men clearance',priority:100},{url:'https://www.walmart.com/c/best-sellers/men-clothes-in-clearance',label:'Men best',priority:95},{url:'https://www.walmart.com/shop/deals/clearance',label:'All clearance',priority:90}],queued=new Set(queue.map(x=>x.url)),found=new Map();let pages=0,lanes=0;while(queue.length){queue.sort((a,b)=>b.priority-a.priority);const lane=queue.shift();let page=1,stale=0,prev='';const laneIds=new Set();while(true){st.textContent=`${lane.label} · page ${page} · ${found.size} live items`;let html;try{html=await webFetch(pageUrl(lane.url,page))}catch{break}pages++;for(const l of discoverLanes(html)){if(!queued.has(l.url)){queued.add(l.url);queue.push(l)}}const batch=looseProducts(html,lane.label),ids=batch.map(x=>String(x.id)),fp=ids.slice().sort().join(',');let fresh=0;for(const p of batch){if(!laneIds.has(String(p.id))){laneIds.add(String(p.id));fresh++}found.set(String(p.id),{...(found.get(String(p.id))||{}),...p,scanId,active:true})}if(!batch.length||fp===prev||fresh===0)stale++;else stale=0;prev=fp;if(!batch.length||stale>=2)break;page++;await new Promise(r=>setTimeout(r,350))}lanes++}const old=new Map(products.map(p=>[String(p.id),p]));for(const [id,p] of found){const o=old.get(id);old.set(id,{...o,...p,firstSeen:o?.firstSeen||Date.now(),history:[...(o?.history||[]),{t:Date.now(),p:+p.price}].slice(-120)})}products=[...old.values()].map(p=>p.scanId===scanId?p:{...p,active:false});saveState();t.textContent='Scan complete';st.textContent=`${found.size} verified in-stock listing items · ${pages} pages · ${lanes} clearance lanes. Visible cards verify exact product photos.`;render()}
function shareApp(){if(window.AndroidBridge&&AndroidBridge.share)AndroidBridge.share('LUX//CLEARANCE Personal',location.href);else if(navigator.share)navigator.share({title:'LUX//CLEARANCE Personal',text:'LUX//CLEARANCE',url:location.href}).catch(()=>{});else navigator.clipboard?.writeText(location.href)}
document.getElementById('q').addEventListener('input',()=>{renderLimit=120;render()});document.getElementById('max').addEventListener('change',()=>{renderLimit=120;render()});document.getElementById('sort').addEventListener('change',render);chips();render();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}